name: mkdocs
channels:
  - defaults
dependencies:
  - python=3.11.8
  - pip
  - pip :
    - material
    - mkdocs-awesome-pages-plugin
    - mkdocs-git-authors-plugin
    - mkdocs-git-committers-plugin-2
    - mkdocs-git-revision-date-localized-plugin
    - mkdocs-glightbox
    - mkdocs-material[imaging]
    - mkdocs-minify-plugin
    - mkdocs-monorepo-plugin
    - mkdocs-pdf-export-plugin
    - mkdocs-same-dir
    - mkdocstrings[crystal,python]
    - mkdocs-with-pdf
    - pymdown-extensions
prefix: /opt/conda/envs/mkdocs
